name: Deploy to Minikube

on:
  push:
    branches:
      - main  # change to your branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Decode kubeconfig and set up config
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBECONFIG_DATA }}" | base64 -d > $HOME/.kube/config

    - name: Apply Kubernetes Deployment
      run: kubectl apply -f k8s/deployment.yaml

    - name: Apply Kubernetes Service
      run: kubectl apply -f k8s/service.yaml

    - name: Get all resources
      run: kubectl get all -o wide
